"""Recommendation engine orchestration: rules + signals -> persisted run."""
from __future__ import annotations

import uuid

from sqlalchemy.orm import Session

from ...models.reco import Recommendation
from .. import portfolio as psvc
from .rules import (
    RecoDraft,
    check_allocation_drift,
    check_concentration,
    check_currency_exposure,
    check_tax_flags,
)
from .signals import instrument_signals

DISCLAIMER = ("Informational signals generated by rule-based analysis — not investment "
              "advice, and not a substitute for a SEBI-registered adviser.")


def generate_drafts(db: Session) -> list[RecoDraft]:
    holdings = psvc.build_holdings(db)
    prices = psvc.latest_prices(db, list(holdings.keys()))
    usdinr = psvc.latest_fx(db)
    base = "INR"

    class_values: dict[str, float] = {}
    for iid, h in holdings.items():
        if h.quantity > 0 and iid in prices:
            v = psvc.to_base_f(float(h.quantity) * prices[iid][1],
                               h.instrument.currency, base, usdinr)
            if v is None:
                continue
            cls = h.instrument.asset_class
            class_values[cls] = class_values.get(cls, 0) + v
    for asset in psvc.manual_assets_total(db):
        v = psvc.to_base_f(float(asset.current_value), asset.currency, base, usdinr)
        if v is not None:
            class_values[asset.asset_class] = class_values.get(asset.asset_class, 0) + v

    drafts: list[RecoDraft] = []
    drafts += check_concentration(holdings, prices, usdinr, base)
    drafts += check_currency_exposure(holdings, prices, usdinr, base)
    drafts += check_allocation_drift(db, class_values)
    drafts += check_tax_flags(holdings, prices)
    drafts += instrument_signals(db, holdings)
    return drafts


def run_recommendation_engine(db: Session) -> int:
    run_id = str(uuid.uuid4())
    drafts = generate_drafts(db)
    for d in drafts:
        db.add(Recommendation(
            run_id=run_id, kind=d.kind, category=d.category, severity=d.severity,
            instrument_id=d.instrument_id, title=d.title, rationale=d.rationale,
            data=d.data,
        ))
    db.commit()
    return len(drafts)
